POST http://localhost:6050/api/exhibitions/new-exhibition
Content-Type: application/json

{
    "artspace": "demo artspace",
    "title": "The show about yellow",
    "rovers": "6076b0703d02011cee43996f",
    "description": "Lorem Ipsum",
    "openingDay": "22.09.2021",
    "closingDay": "29.11.2022",
    "bannerImage": "https://brimboria.net/wp-content/uploads/2021/04/demo2.jpg"
}